runtime: custom
env: flex
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 7  
resources:
      memory_gb: 2
beta_settings:
    cloud_sql_instances: vefast:southamerica-east1:vefast-dev=tcp:3306
